---
kind: pipeline
type: docker
name: default

steps:

- name: test and docs
  image: python:3.8-slim
  commands:
  - pip install pdoc3==0.9.2
  - pip install -r requirements.txt
  - pytest
  - rm -rf ./docs/linq/
  - pdoc3 ./linq --html -o docs

- name: push
  image: alpine/git
  commands:
  - git add docs
  - git config user.name drone
  - git config user.email drone
  - git commit -m "[CI SKIP]" --allow-empty
  - git push origin master

trigger:
  branch:
  - master
  event:
  - push