---
kind: pipeline
type: docker
name: default

steps:
- name: test and docs
  image: python:3.8-slim
  commands:
  - pip install -r requirements.txt
  - pytest
  - rm -rf ./docs/linq/
  - pip install pdoc3==0.9.2
  - pdoc3 ./linq --html -o docs
- name: publish
  image: python:3.8-slim
  environment:
    PYPI_USERNAME:
      from_secret: PYPI_USERNAME
    PYPI_PASSWORD:
      from secret: PYPI_PASSWORD
  commands:
    - pip install twine -r requirements.txt
    - python scripts/publish_if_new_version.py
- name: push
  image: alpine/git
  commands:
  - git add docs
  - git config user.name drone
  - git config user.email drone
  - git commit -m "[CI SKIP]" --allow-empty
  - git push origin master

trigger:
  branch:
  - master
  event:
  - push

---
kind: pipeline
type: docker
name: pull request

steps:
- name: test
  image: python:3.8-slim
  commands:
  - pip install -r requirements.txt
  - pytest

trigger:
  event:
  - pull_request